version: '3'
services:
  scheduler:
    build:
      context: ./instant-meet-api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    entrypoint: 'java -jar /app/app.jar'
    networks:
      - app-net
  db:
    image: mysql:8.0
    ports:
      - '52984:3306'
    volumes:
      - ./mysql/settings:/etc/mysql/conf.d/
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_USER: myuser
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
