version: '3'
services:
  scheduler:
    build: # customizeする必要がある時
      context: ./instant-meet-api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    entrypoint: 'java -jar /app/app.jar'
    #volumes:
    #  - ./instant-meet-api:/app # ホストのディレクトリをコンテナのディレクトリにマッピング