spring:
  datasource:
    url: jdbc:mysql://localhost:52984/mydatabase
    username: myuser
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect