spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/scheduler
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect